
// Admin Part
 ###
POST http://localhost:3000/api/Admin
Content-Type: application/json

{

"name": "Admiwn",
"email": "Adminw@gmail.com",
"identifiant": "wzz",
"phone": "12w3",
"CIN": "eew",
"password": "1w50"
}
###
GET http://localhost:3000/api/Admin

### 
GET http://localhost:3000/api/Admin/63babfe58f44c4f4e3304aff
###
PUT http://localhost:3000/api/Admin/63babfe58f44c4f4e3304aff
Content-Type: application/json

{

"name": "Admin",
"email": "updatedAdmin@gmail.com",
"identifiant": "CIN",
"phone": "123",
"password": "150"
}

###
DELETE  http://localhost:3000/api/Admin/:id
// User Part
###
POST http://localhost:3000/api/User
Content-Type: application/json

{

"name": "user",
"email": "user@gmail.com",
"identifiant": "123-321",
"phone":"aa",
"password": "user"
}

###
GET http://localhost:3000/api/User

### 
GET http://localhost:3000/api/User/login
Content-Type: application/json

{
"email": "user@gmail.com",
"password": "user"

}
###
PUT http://localhost:3000/api/User/63babfa6d2ddedabbfa25864
Content-Type: application/json

{

"name": "User",
"email": "updaateduser@gmail.com",
"identifiant": "CINa",
"password": "150"
}

###
DELETE  http://localhost:3000/api/User/63b97c7f5595d16054eac565

// Account Part

###
POST http://localhost:3000/api/Account
Content-Type: application/json

{

"identifiant": "aa",
"solde": "hello",
"transaction": "hello"
}


###
GET http://localhost:3000/api/Account

### 
GET http://localhost:3000/api/Account/63bad2d9f5d2a2b4d8dd1486
###
PUT http://localhost:3000/api/Account/:id
Content-Type: application/json

{


"identifiant": "hello",
"solde": "hello",
"transaction": "hello"
}

###
DELETE  http://localhost:3000/api/User/63b97c7f5595d16054eac565
